### ISSUE TITLE
New SDK build

### ISSUE THREAD

**Issue by mrkruvasan** [this-username-has-been-taken/amneziawg-openwrt#68]
Hi, I'm having a problem with the new way of building packages. If I uncheck the box to skip Go, the build fails. I'm attaching the build log.

[logs_46257878940.zip](https://github.com/user-attachments/files/22536100/logs_46257878940.zip)

**Comment by this-username-has-been-taken** [comment]
Hi!

Thank you for reporting the issue!
My bad: I forgot to skip Go lang update if Go package compilation was not requested. I have fixed it.
Please sync the fork and re-run the build.

**Comment by mrkruvasan** [comment]
Synced the fork, the error persists.

[logs_46260607509.zip](https://github.com/user-attachments/files/22536974/logs_46260607509.zip)

**Comment by this-username-has-been-taken** [comment]
That's another error.
Judging by the output, the OpenWrt git repository (https://git.openwrt.org/) went for a "coffee break" and returned code 503 (Service Unavailable). As a result, the feeds script couldn’t update the sources. This can happen from time to time, so just re-run the workflow in 10–15 minutes. 
This issue is not related to my repository but is caused by the external repository being temporarily unavailable.
I have successfully executed the workflow for [24.10.3 - aarch64_cortex-a53 - mediatek/filogic](https://github.com/this-username-has-been-taken/amneziawg-openwrt/actions/runs/18007949424)

**Comment by mrkruvasan** [comment]
I ran it again and everything worked without errors. Thank you.

**Comment by this-username-has-been-taken** [comment]
Great!
The bug with the Go update has been fixed.
